name: "Scrypted"
version: "v0.4.1"
slug: scrypted
description: "A home automation platform powered by node.js"
url: "https://github.com/koush/scrypted"
arch:
  - aarch64
  - amd64
  - armv7
image: koush/scrypted
host_network: true
devices:
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
usb: true
ingress: false
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
webui: "http://[HOST]:[PORT:11080]"
stage: experimental
advanced: true
init: false
hassio_role: default
